# Etapa 1: Build da aplicação .NET
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Copia os arquivos do projeto e restaura as dependências
COPY ["Documents.WebApi/Documents.WebApi.csproj", "Documents.WebApi/"]
COPY ["Documents.Infrastructure/Documents.Infrastructure.csproj", "Documents.Infrastructure/"]
COPY ["Documents.Application/Documents.Application.csproj", "Documents.Application/"]

RUN dotnet restore "Documents.WebApi/Documents.WebApi.csproj"

# Copia o restante dos arquivos do projeto e publica a aplicação
COPY . ./
RUN dotnet publish "Documents.WebApi/Documents.WebApi.csproj" -c Release -o /app/publish

# Etapa 2: Criação da imagem final
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app
COPY --from=build /app/publish .

# Expõe a porta 80
EXPOSE 80
ENTRYPOINT ["dotnet", "Documents.WebApi.dll"]