name: Docker Publish

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar projeto do GitHub
        uses: actions/checkout@v3

      - name: Fazer login no Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Gerar imagem Docker do backend
        run: docker-compose -f src/docker-compose.yml build

      - name: Enviar imagem pro Docker Hub
        run: docker push andersonluizdealmeida1997/almeida-pinturas-backend:latest
