name: Docker Publish

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar projeto do GitHub
        uses: actions/checkout@v3

      - name: Fazer login no Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Gerar imagem Docker do backend
        run: docker compose -f docker-compose.yml build

      - name: Tag a imagem com a versão mais recente
        run: |
          docker tag andersonluizdealmeida1997/almeida-pinturas:latest andersonluizdealmeida1997/almeida-pinturas:${{ github.sha }}

      - name: Enviar imagem pro Docker Hub (latest)
        run: docker push andersonluizdealmeida1997/almeida-pinturas:latest

      - name: Enviar versão específica para o Docker Hub
        run: docker push andersonluizdealmeida1997/almeida-pinturas:${{ github.sha }}
