name: Docker Publish

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Login no Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build da imagem
        run: docker build -t andersonluizdealmeida1997/almeida-pinturas-backend:latest .

      - name: Push da imagem para o Docker Hub
        run: docker push andersonluizdealmeida1997/almeida-pinturas-backend:latest
